### ISSUE TITLE
"Add card" button appears even when not in email opening mode

### ISSUE THREAD

**Issue by tungnguyenson** [tungnguyenson/gmail-to-trello-extension#3]
Reproduce:
1. Open an email
2. Quickly switch to list mode

**Comment by acoven** [comment]
There's a lot of messages that seem to back up and/or get lost; I noticed this once but haven't been able to consistently repro. It depends a lot on whether you're in developer mode in the browser and how many extensions it's loading before.

**Comment by acoven** [comment]
Better repro steps:

1. Clear out one of your gmail "labels" so that there's no messages in it
2. Go to your InBox or somewhere that has messages
3. Click on the message
4. Click on Add Card
5. Pick a Trello board
6. Once everything's loaded, click the GTT Close box
7. Switch to the gmail label that displays "No messages" in it

Result:
Add card still present despite "No messages"; clicking on "Add card" then shows old data and causes toolbar to get additional copies of links, etc.

Expected:
Add card button to disable or disappear when switching to the "No messages" box

**Comment by acoven** [comment]
Turns out this is a feature. People like the Add Card button to be persistent. So closing NeverFix.
